language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install --dev
  - mkdir -p build/logs
  - ./app/Console/cake schema create Users.users

script:
    - ./app/Console/cake test app AllTests --stderr --coverage-clover build/logs/clover.xml --include-path vendor/phpunit/phpunit

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: false
